# Generated by Django 3.0.5 on 2020-04-06 22:41

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=200)),
                ('current_cases', models.IntegerField(default=0)),
                ('geom', djgeojson.fields.PolygonField()),
            ],
        ),
    ]
