# Generated by Django 3.0.5 on 2020-04-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaborone', '0002_condition_patient_support_symptom'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='plot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
