# Generated by Django 3.0.5 on 2020-04-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaborone', '0004_auto_20200414_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='test_result',
            field=models.BooleanField(blank=True, help_text='If yes, what was the result?', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='conditions',
            field=models.ManyToManyField(help_text="Patient's Pre-exsisting Conditions", to='gaborone.Condition'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='has_had_contact',
            field=models.BooleanField(help_text='Have you had contact with anyone infected by the Coronavirus'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='has_tested',
            field=models.BooleanField(blank=True, help_text='Have you been tested', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='has_travelled',
            field=models.BooleanField(help_text='Have you travled outside of Botswana in the last month'),
        ),
    ]
