# Generated by Django 3.0.5 on 2020-04-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaborone', '0005_auto_20200414_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='has_travelled',
            field=models.BooleanField(help_text='Have you traveled outside of Botswana in the last month'),
        ),
    ]
